

spring:
  application:
    name: provider

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/euraka/
server:
  port: 8012