spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/euraka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8011