#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      default-zone: http://${eureka.instance.hostname}:${server.port}/euraka/
#  server:
#    wait-time-in-ms-when-sync-empty: 0
#    enable-self-preservation: false
#spring:
#  application:
#    name: eureke-server