server:
  port: 8762
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/euraka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false